function features_data = create_features(hist_fund_data)
   
    new_features = {'Shares Outstanding	', 'Stock Adjusted Closing Price', ...
       'Log Revenue Return', 'Current Assets / Total Assets', ...
       '(Current Assets - Stock) / Total Assets', 'Current Liabilities / Total Assets', ...
       'Cash / Current Liabilities', 'Cash / Total Assets', 'Cash / Total Debt', ...
       'Net Op. Work. Capital / Total Assets', 'Long Term Debt / Total Assets', ...
       'Total Debt / Total Assets', 'EBIDTA / Total Assets', 'Net Income / Total Assets', ...
       'Total Sales / Total Assets', 'Operating Cash Flow / Total Assets', ...
       'Operating Cash Flow / Total Sales', 'Current Assets / Total Sales', ...
       'Net Op. Work. Capital / Total Sales', 'Accounts Payable / Total Sales', ...
       'Accounts Receivable / Total Sales', 'Inventory / Total Sales', ...
       'Cash / Total Sales', 'Operating Profit', 'Return on Average Equity', ...
       'Total Liabilities', 'Funds from Operations', 'Operating Margin', ...
       'Interest Coverage', 'Fixed Asset Turnover', 'Total Asset Turnover', ...
       'Cash Ratio', 'Net Asset Value ', 'Earnings Per Share', 'EBITDA Per Share', ...
       'Dividend Per Share', 'Total Assets / NAV', 'Total Assets / NAV Trend ', ...
       'Earnings YoY', 'NAV YoY', 'Revenue YoY', 'Earnings YoY Trend', ...
       'NAV YoY Trend', 'Revenue YoY Trend', 'Beta'}; 
   
   % Use this just to get a list of the variables
   dummy_var = 'A';
   ratio_start = 212;
   existing_features = hist_fund_data.(dummy_var)(1, :)';
   existing_features = existing_features(ratio_start:end)';
   bad_features = {'RATIOS CALCULATIONS', 'PROFIT MARGINS', 'NORMALIZED RATIOS', ...
       'SOLVENCY RATIOS', 'EFFICIENCY RATIOS', 'ACTIVITY RATIOS', 'LIQUIDITY RATIOS', ...
       'CAPITAL STRUCTURE RATIOS', 'PROFITABILITY', 'AGAINST THE INDUSTRY RATIOS'};
   
   full_features = cat(2, setdiff(existing_features, bad_features), new_features);
   features_data = {};
end